
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO
{

using System;
    using System.Collections.Generic;
    
public partial class BankBookSet
{

    public System.Guid BankBookId { get; set; }

    public short cache { get; set; }

    public System.Guid Credit_CreditId { get; set; }



    public virtual CreditSet CreditSet { get; set; }

}

}
