//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credit()
        {
            this.BankBooks = new HashSet<BankBook>();
            this.Payments = new HashSet<Payments>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public double Percent { get; set; }
        public int StartSum { get; set; }
        public int AllSum { get; set; }
        public int PayCount { get; set; }
        public string Status { get; set; }
        public double Penya { get; set; }
        public int PayMounth { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid ManagerId { get; set; }
        public System.Guid CreditTypeId { get; set; }
        public Nullable<System.Guid> DebtsId { get; set; }
        public int Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankBook> BankBooks { get; set; }
        public virtual CreditType CreditTypes { get; set; }
        public virtual Debts Debts { get; set; }
        public virtual Manager Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Person Persons { get; set; }
    }
}
