
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO
{

using System;
    using System.Collections.Generic;
    
public partial class CreditTypesSet
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CreditTypesSet()
    {

        this.CreditSets = new HashSet<CreditSet>();

    }


    public System.Guid CreditTypesId { get; set; }

    public double Percent { get; set; }

    public double StartSumPercent { get; set; }

    public short PayCount { get; set; }

    public string Info { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CreditSet> CreditSets { get; set; }

}

}
