
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO
{

using System;
    using System.Collections.Generic;
    
public partial class CreditSet
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CreditSet()
    {

        this.BankBookSets = new HashSet<BankBookSet>();

        this.PaymentsSets = new HashSet<PaymentsSet>();

    }


    public System.Guid CreditId { get; set; }

    public System.DateTime DateStart { get; set; }

    public System.DateTime DateEnd { get; set; }

    public double Percent { get; set; }

    public short StartSum { get; set; }

    public short AllSum { get; set; }

    public short PayCount { get; set; }

    public string Status { get; set; }

    public double Penya { get; set; }

    public short PayMounth { get; set; }

    public System.Guid PersonPersonId { get; set; }

    public System.Guid ManagerManagerId { get; set; }

    public System.Guid CreditTypes_CreditTypesId { get; set; }

    public Nullable<System.Guid> Debts_DebtsId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BankBookSet> BankBookSets { get; set; }

    public virtual CreditTypesSet CreditTypesSet { get; set; }

    public virtual DebtsSet DebtsSet { get; set; }

    public virtual ManagerSet ManagerSet { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PaymentsSet> PaymentsSets { get; set; }

    public virtual PersonSet PersonSet { get; set; }

}

}
