//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LalkaBankDabaseModelContainer : DbContext
    {
        public LalkaBankDabaseModelContainer()
            : base("name=LalkaBankDabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankBookSet> BankBookSets { get; set; }
        public virtual DbSet<CreditSet> CreditSets { get; set; }
        public virtual DbSet<CreditTypesSet> CreditTypesSets { get; set; }
        public virtual DbSet<DebtsSet> DebtsSets { get; set; }
        public virtual DbSet<ManagerSet> ManagerSets { get; set; }
        public virtual DbSet<MessageSet> MessageSets { get; set; }
        public virtual DbSet<PassportSet> PassportSets { get; set; }
        public virtual DbSet<PaymentsSet> PaymentsSets { get; set; }
        public virtual DbSet<PersonSet> PersonSets { get; set; }
        public virtual DbSet<RequestSet> RequestSets { get; set; }
        public virtual DbSet<testSet> testSets { get; set; }
    }
}
