
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    public System.Guid Id { get; set; }

    public string Text { get; set; }

    public System.Guid PersonId { get; set; }

    public System.Guid ManagerId { get; set; }

    public System.Guid RequestId { get; set; }



    public virtual Manager Manager { get; set; }

    public virtual Person Persons { get; set; }

    public virtual Request Request { get; set; }

}

}
