//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsSet
    {
        public System.Guid PaymentsId { get; set; }
        public System.DateTime Time { get; set; }
        public string Payment { get; set; }
        public System.Guid Credit_CreditId { get; set; }
    
        public virtual CreditSet CreditSet { get; set; }
    }
}
